<?php

declare(strict_types=1);

/*
 * ZEF Framework v2.7.0 — zero-composer autoloader (static classmap).
 *
 * This autoloader keeps the framework usable WITHOUT Composer, exactly
 * like the original single-file bundle. It is also registered through
 * composer "files" autoload; double registration is safe.
 *
 * - PSR shims are loaded eagerly (same semantics as the monolith), the
 *   interface_exists()/class_exists() guards make them no-ops when the
 *   official PSR packages are already installed.
 * - Everything else resolves lazily through the static classmap below.
 */

if (!function_exists('zef_framework_autoload')) {
    function zef_framework_autoload(string $class): void
    {
        static $map = null;
        if ($map === null) {
            $map = [
                "Zef\\App\\Bootstrap" => __DIR__ . '/../src/Bootstrap.php',
                "Zef\\Framework\\Application" => __DIR__ . '/../src/Adapters/Kernel/Application.php',
                "Zef\\Framework\\Autowiring\\AutowireClassSpec" => __DIR__ . '/../src/Domain/Autowiring/AutowireClassSpec.php',
                "Zef\\Framework\\Autowiring\\AutowireMetadata" => __DIR__ . '/../src/Domain/Autowiring/AutowireMetadata.php',
                "Zef\\Framework\\Autowiring\\AutowireParameterSpec" => __DIR__ . '/../src/Domain/Autowiring/AutowireParameterSpec.php',
                "Zef\\Framework\\Autowiring\\AutowireResult" => __DIR__ . '/../src/Domain/Autowiring/AutowireResult.php',
                "Zef\\Framework\\Autowiring\\Inject" => __DIR__ . '/../src/Domain/Autowiring/Inject.php',
                "Zef\\Framework\\Autowiring\\Target" => __DIR__ . '/../src/Domain/Autowiring/Target.php',
                "Zef\\Framework\\Autowiring\\Value" => __DIR__ . '/../src/Domain/Autowiring/Value.php',
                "Zef\\Framework\\CQRS\\CommandBus" => __DIR__ . '/../src/Application/CQRS/CommandBus.php',
                "Zef\\Framework\\CQRS\\CommandBusInterface" => __DIR__ . '/../src/Domain/CQRS/CommandBusInterface.php',
                "Zef\\Framework\\CQRS\\CommandHandlerInterface" => __DIR__ . '/../src/Domain/CQRS/CommandHandlerInterface.php',
                "Zef\\Framework\\CQRS\\CqrsBusTrait" => __DIR__ . '/../src/Application/CQRS/CqrsBusTrait.php',
                "Zef\\Framework\\CQRS\\CqrsContext" => __DIR__ . '/../src/Domain/CQRS/CqrsContext.php',
                "Zef\\Framework\\CQRS\\CqrsEventResult" => __DIR__ . '/../src/Domain/CQRS/CqrsEventResult.php',
                "Zef\\Framework\\CQRS\\CqrsHandlerConflictException" => __DIR__ . '/../src/Domain/CQRS/CqrsHandlerConflictException.php',
                "Zef\\Framework\\CQRS\\CqrsHandlerNotFoundException" => __DIR__ . '/../src/Domain/CQRS/CqrsHandlerNotFoundException.php',
                "Zef\\Framework\\CQRS\\CqrsMiddlewareInterface" => __DIR__ . '/../src/Domain/CQRS/CqrsMiddlewareInterface.php',
                "Zef\\Framework\\CQRS\\IdempotencyStoreInterface" => __DIR__ . '/../src/Domain/CQRS/IdempotencyStoreInterface.php',
                "Zef\\Framework\\CQRS\\IdempotencyTrait" => __DIR__ . '/../src/Application/CQRS/IdempotencyTrait.php',
                "Zef\\Framework\\CQRS\\InMemoryIdempotencyStore" => __DIR__ . '/../src/Application/CQRS/InMemoryIdempotencyStore.php',
                "Zef\\Framework\\CQRS\\QueryBus" => __DIR__ . '/../src/Application/CQRS/QueryBus.php',
                "Zef\\Framework\\CQRS\\QueryBusInterface" => __DIR__ . '/../src/Domain/CQRS/QueryBusInterface.php',
                "Zef\\Framework\\CQRS\\QueryHandlerInterface" => __DIR__ . '/../src/Domain/CQRS/QueryHandlerInterface.php',
                "Zef\\Framework\\Cache\\CacheClockInterface" => __DIR__ . '/../src/Domain/Cache/CacheClockInterface.php',
                "Zef\\Framework\\Cache\\CacheInterface" => __DIR__ . '/../src/Domain/Cache/CacheInterface.php',
                "Zef\\Framework\\Cache\\CacheItem" => __DIR__ . '/../src/Domain/Cache/CacheItem.php',
                "Zef\\Framework\\Cache\\CacheKeyNormalizerInterface" => __DIR__ . '/../src/Domain/Cache/CacheKeyNormalizerInterface.php',
                "Zef\\Framework\\Cache\\CacheSerializerInterface" => __DIR__ . '/../src/Domain/Cache/CacheSerializerInterface.php',
                "Zef\\Framework\\Cache\\CacheStoreInterface" => __DIR__ . '/../src/Domain/Cache/CacheStoreInterface.php',
                "Zef\\Framework\\Cache\\DefaultCacheKeyNormalizer" => __DIR__ . '/../src/Infrastructure/Cache/DefaultCacheKeyNormalizer.php',
                "Zef\\Framework\\Cache\\InMemoryCache" => __DIR__ . '/../src/Infrastructure/Cache/InMemoryCache.php',
                "Zef\\Framework\\Cache\\InMemoryCacheStore" => __DIR__ . '/../src/Infrastructure/Cache/InMemoryCacheStore.php',
                "Zef\\Framework\\Cache\\InMemoryLockStore" => __DIR__ . '/../src/Application/Cache/InMemoryLockStore.php',
                "Zef\\Framework\\Cache\\LockStoreInterface" => __DIR__ . '/../src/Domain/Cache/LockStoreInterface.php',
                "Zef\\Framework\\Cache\\SystemCacheClock" => __DIR__ . '/../src/Infrastructure/Cache/SystemCacheClock.php',
                "Zef\\Framework\\Cache\\TaggableCache" => __DIR__ . '/../src/Infrastructure/Cache/TaggableCache.php',
                "Zef\\Framework\\Cache\\TieredCache" => __DIR__ . '/../src/Infrastructure/Cache/TieredCache.php',
                "Zef\\Framework\\Config\\AbstractModule" => __DIR__ . '/../src/Infrastructure/Config/AbstractModule.php',
                "Zef\\Framework\\Config\\ConfigAggregator" => __DIR__ . '/../src/Infrastructure/Config/ConfigAggregator.php',
                "Zef\\Framework\\Config\\ConfigProviderInterface" => __DIR__ . '/../src/Domain/Config/ConfigProviderInterface.php',
                "Zef\\Framework\\Config\\ConfigProviderModule" => __DIR__ . '/../src/Infrastructure/Config/ConfigProviderModule.php',
                "Zef\\Framework\\Config\\ConfigurationGovernance" => __DIR__ . '/../src/Domain/Config/ConfigurationGovernance.php',
                "Zef\\Framework\\Config\\ConfigurationSnapshot" => __DIR__ . '/../src/Domain/Config/ConfigurationSnapshot.php',
                "Zef\\Framework\\Config\\EnvironmentSecretProvider" => __DIR__ . '/../src/Infrastructure/Config/EnvironmentSecretProvider.php',
                "Zef\\Framework\\Config\\ModuleConfigProvider" => __DIR__ . '/../src/Infrastructure/Config/ModuleConfigProvider.php',
                "Zef\\Framework\\Config\\ModuleContext" => __DIR__ . '/../src/Domain/Config/ModuleContext.php',
                "Zef\\Framework\\Config\\ModuleDefinition" => __DIR__ . '/../src/Domain/Config/ModuleDefinition.php',
                "Zef\\Framework\\Config\\ModuleInterface" => __DIR__ . '/../src/Domain/Config/ModuleInterface.php',
                "Zef\\Framework\\Config\\ModuleRegistrar" => __DIR__ . '/../src/Domain/Config/ModuleRegistrar.php',
                "Zef\\Framework\\Config\\ModuleRegistry" => __DIR__ . '/../src/Infrastructure/Config/ModuleRegistry.php',
                "Zef\\Framework\\Config\\SecretProviderInterface" => __DIR__ . '/../src/Domain/Config/SecretProviderInterface.php',
                "Zef\\Framework\\Config\\SecretValue" => __DIR__ . '/../src/Domain/Config/SecretValue.php',
                "Zef\\Framework\\Console\\ConsoleException" => __DIR__ . '/../src/Infrastructure/Console/ConsoleException.php',
                "Zef\\Framework\\Console\\ConsoleIO" => __DIR__ . '/../src/Infrastructure/Console/ConsoleIO.php',
                "Zef\\Framework\\Console\\GeneratorInterface" => __DIR__ . '/../src/Infrastructure/Console/GeneratorInterface.php',
                "Zef\\Framework\\Console\\InvalidNameException" => __DIR__ . '/../src/Infrastructure/Console/InvalidNameException.php',
                "Zef\\Framework\\Console\\NamingRules" => __DIR__ . '/../src/Infrastructure/Console/NamingRules.php',
                "Zef\\Framework\\Console\\ScaffoldCollisionException" => __DIR__ . '/../src/Infrastructure/Console/ScaffoldCollisionException.php',
                "Zef\\Framework\\Console\\ScaffoldWriter" => __DIR__ . '/../src/Infrastructure/Console/ScaffoldWriter.php',
                "Zef\\Framework\\Console\\ScaffoldWriteException" => __DIR__ . '/../src/Infrastructure/Console/ScaffoldWriteException.php',
                "Zef\\Framework\\Console\\ZefMaker" => __DIR__ . '/../src/Infrastructure/Console/ZefMaker.php',
                "Zef\\Framework\\Console\\Generator\\CommandGenerator" => __DIR__ . '/../src/Infrastructure/Console/Generator/CommandGenerator.php',
                "Zef\\Framework\\Console\\Generator\\ConfigGenerator" => __DIR__ . '/../src/Infrastructure/Console/Generator/ConfigGenerator.php',
                "Zef\\Framework\\Console\\Generator\\EntityGenerator" => __DIR__ . '/../src/Infrastructure/Console/Generator/EntityGenerator.php',
                "Zef\\Framework\\Console\\Generator\\HandlerGenerator" => __DIR__ . '/../src/Infrastructure/Console/Generator/HandlerGenerator.php',
                "Zef\\Framework\\Console\\Generator\\MiddlewareGenerator" => __DIR__ . '/../src/Infrastructure/Console/Generator/MiddlewareGenerator.php',
                "Zef\\Framework\\Console\\Generator\\ModuleGenerator" => __DIR__ . '/../src/Infrastructure/Console/Generator/ModuleGenerator.php',
                "Zef\\Framework\\Console\\Generator\\PluginGenerator" => __DIR__ . '/../src/Infrastructure/Console/Generator/PluginGenerator.php',
                "Zef\\Framework\\Console\\Generator\\QueryGenerator" => __DIR__ . '/../src/Infrastructure/Console/Generator/QueryGenerator.php',
                "Zef\\Framework\\Console\\Generator\\ServiceGenerator" => __DIR__ . '/../src/Infrastructure/Console/Generator/ServiceGenerator.php',
                "Zef\\Framework\\Console\\Generator\\ValueObjectGenerator" => __DIR__ . '/../src/Infrastructure/Console/Generator/ValueObjectGenerator.php',
                "Zef\\Framework\\Console\\Inspector\\ConfigShower" => __DIR__ . '/../src/Infrastructure/Console/Inspector/ConfigShower.php',
                "Zef\\Framework\\Console\\Inspector\\ModuleLister" => __DIR__ . '/../src/Infrastructure/Console/Inspector/ModuleLister.php',
                "Zef\\Framework\\Console\\Inspector\\PluginLister" => __DIR__ . '/../src/Infrastructure/Console/Inspector/PluginLister.php',
                "Zef\\Framework\\Constant\\HttpReasonPhrases" => __DIR__ . '/../src/Domain/Constant/HttpReasonPhrases.php',
                "Zef\\Framework\\Container\\Autowiring\\AutowireAotCompiler" => __DIR__ . '/../src/Application/Container/Autowiring/AutowireAotCompiler.php',
                "Zef\\Framework\\Container\\Autowiring\\AutowireCompilerPass" => __DIR__ . '/../src/Application/Container/Autowiring/AutowireCompilerPass.php',
                "Zef\\Framework\\Container\\Autowiring\\ReflectionMetadataExtractor" => __DIR__ . '/../src/Application/Container/Autowiring/ReflectionMetadataExtractor.php',
                "Zef\\Framework\\Container\\BootableProviderInterface" => __DIR__ . '/../src/Domain/Container/ServiceProviderInterface.php',
                "Zef\\Framework\\Container\\CompiledContainerPlan" => __DIR__ . '/../src/Application/Container/CompiledContainerPlan.php',
                "Zef\\Framework\\Container\\Container" => __DIR__ . '/../src/Application/Container/Container.php',
                "Zef\\Framework\\Container\\ContainerCompiler" => __DIR__ . '/../src/Application/Container/ContainerCompiler.php',
                "Zef\\Framework\\Container\\ContainerResolver" => __DIR__ . '/../src/Application/Container/ContainerResolver.php',
                "Zef\\Framework\\Container\\ContextualBindingBuilder" => __DIR__ . '/../src/Application/Container/ContextualBindingBuilder.php',
                "Zef\\Framework\\Container\\DeferrableProviderInterface" => __DIR__ . '/../src/Domain/Container/ServiceProviderInterface.php',
                "Zef\\Framework\\Container\\FailFastInitializationGuard" => __DIR__ . '/../src/Application/Container/FailFastInitializationGuard.php',
                "Zef\\Framework\\Container\\InitializationGuard" => __DIR__ . '/../src/Domain/Container/InitializationGuard.php',
                "Zef\\Framework\\Container\\NamespaceRadixTree" => __DIR__ . '/../src/Domain/Container/NamespaceRadixTree.php',
                "Zef\\Framework\\Container\\RadixTreeCompilerPass" => __DIR__ . '/../src/Application/Container/RadixTreeCompilerPass.php',
                "Zef\\Framework\\Container\\RequestScope" => __DIR__ . '/../src/Application/Container/RequestScope.php',
                "Zef\\Framework\\Container\\ResolutionContext" => __DIR__ . '/../src/Application/Container/ResolutionContext.php',
                "Zef\\Framework\\Container\\ServiceDefinition" => __DIR__ . '/../src/Domain/Container/ServiceDefinition.php',
                "Zef\\Framework\\Container\\ServiceLifetime" => __DIR__ . '/../src/Domain/Container/ServiceLifetime.php',
                "Zef\\Framework\\Container\\ServiceProviderInterface" => __DIR__ . '/../src/Domain/Container/ServiceProviderInterface.php',
                "Zef\\Framework\\Container\\ServiceRegistrar" => __DIR__ . '/../src/Application/Container/ServiceRegistrar.php',
                "Zef\\Framework\\Container\\ServiceRegistry" => __DIR__ . '/../src/Application/Container/ServiceRegistry.php',
                "Zef\\Framework\\Container\\ServiceRegistryView" => __DIR__ . '/../src/Application/Container/ServiceRegistryView.php',
                "Zef\\Framework\\Container\\TaggedServiceLocator" => __DIR__ . '/../src/Application/Container/TaggedServiceLocator.php',
                "Zef\\Framework\\Dispatcher" => __DIR__ . '/../src/Adapters/Kernel/Dispatcher.php',
                "Zef\\Framework\\Event\\EventBusInterface" => __DIR__ . '/../src/Domain/Event/EventBusInterface.php',
                "Zef\\Framework\\Event\\EventContext" => __DIR__ . '/../src/Domain/Event/EventContext.php',
                "Zef\\Framework\\Event\\EventDispatchException" => __DIR__ . '/../src/Domain/Event/EventDispatchException.php',
                "Zef\\Framework\\Event\\EventDispatcher" => __DIR__ . '/../src/Application/Event/EventDispatcher.php',
                "Zef\\Framework\\Event\\EventRegistration" => __DIR__ . '/../src/Domain/Event/EventRegistration.php',
                "Zef\\Framework\\Event\\EventSubscriberInterface" => __DIR__ . '/../src/Domain/Event/EventSubscriberInterface.php',
                "Zef\\Framework\\Exception\\ApiVersionUnsupportedException" => __DIR__ . '/../src/Domain/Exception/ApiVersionUnsupportedException.php',
                "Zef\\Framework\\Exception\\CircularAliasException" => __DIR__ . '/../src/Domain/Exception/CircularAliasException.php',
                "Zef\\Framework\\Exception\\ConcurrentServiceInitializationException" => __DIR__ . '/../src/Domain/Exception/ConcurrentServiceInitializationException.php',
                "Zef\\Framework\\Exception\\InvalidConfigurationException" => __DIR__ . '/../src/Domain/Exception/InvalidConfigurationException.php',
                "Zef\\Framework\\Exception\\InvalidFactoryException" => __DIR__ . '/../src/Domain/Exception/InvalidFactoryException.php',
                "Zef\\Framework\\Exception\\InvalidHeaderException" => __DIR__ . '/../src/Domain/Exception/InvalidHeaderException.php',
                "Zef\\Framework\\Exception\\MethodNotAllowedException" => __DIR__ . '/../src/Domain/Exception/MethodNotAllowedException.php',
                "Zef\\Framework\\Exception\\ModuleDependencyViolationException" => __DIR__ . '/../src/Domain/Exception/ModuleDependencyViolationException.php',
                "Zef\\Framework\\Exception\\PayloadTooLargeException" => __DIR__ . '/../src/Domain/Exception/PayloadTooLargeException.php',
                "Zef\\Framework\\Exception\\RouteConstraintException" => __DIR__ . '/../src/Domain/Exception/RouteConstraintException.php',
                "Zef\\Framework\\Exception\\RouteNotFoundException" => __DIR__ . '/../src/Domain/Exception/RouteNotFoundException.php',
                "Zef\\Framework\\Exception\\ServiceCircularDependencyException" => __DIR__ . '/../src/Domain/Exception/ServiceCircularDependencyException.php',
                "Zef\\Framework\\Exception\\ServiceNotFoundException" => __DIR__ . '/../src/Domain/Exception/ServiceNotFoundException.php',
                "Zef\\Framework\\Exception\\ServiceResolutionException" => __DIR__ . '/../src/Domain/Exception/ServiceResolutionException.php',
                "Zef\\Framework\\Foundation\\Env" => __DIR__ . '/../src/Infrastructure/Foundation/Env.php',
                "Zef\\Framework\\Foundation\\ZefVersion" => __DIR__ . '/../src/Domain/Foundation/ZefVersion.php',
                "Zef\\Framework\\Http\\ApiVersion" => __DIR__ . '/../src/Adapters/Http/ApiVersion.php',
                "Zef\\Framework\\Http\\ApiVersionNegotiator" => __DIR__ . '/../src/Adapters/Http/ApiVersionNegotiator.php',
                "Zef\\Framework\\Http\\ETagMiddleware" => __DIR__ . '/../src/Adapters/Http/ETagMiddleware.php',
                "Zef\\Framework\\Http\\FormRequest" => __DIR__ . '/../src/Adapters/Http/FormRequest.php',
                "Zef\\Framework\\Http\\JsonResponse" => __DIR__ . '/../src/Adapters/Http/JsonResponse.php',
                "Zef\\Framework\\Http\\LimitedInputStream" => __DIR__ . '/../src/Adapters/Http/LimitedInputStream.php',
                "Zef\\Framework\\Http\\MessageBase" => __DIR__ . '/../src/Adapters/Http/MessageBase.php',
                "Zef\\Framework\\Http\\ProblemDetails" => __DIR__ . '/../src/Adapters/Http/ProblemDetails.php',
                "Zef\\Framework\\Http\\Psr17Factory" => __DIR__ . '/../src/Adapters/Http/Psr17Factory.php',
                "Zef\\Framework\\Http\\Request" => __DIR__ . '/../src/Adapters/Http/Request.php',
                "Zef\\Framework\\Http\\RequestBodyPolicy" => __DIR__ . '/../src/Adapters/Http/RequestBodyPolicy.php',
                "Zef\\Framework\\Http\\RequestFactory" => __DIR__ . '/../src/Adapters/Http/RequestFactory.php',
                "Zef\\Framework\\Http\\RequestTrait" => __DIR__ . '/../src/Adapters/Http/RequestTrait.php',
                "Zef\\Framework\\Http\\Response" => __DIR__ . '/../src/Adapters/Http/Response.php',
                "Zef\\Framework\\Http\\ServerRequest" => __DIR__ . '/../src/Adapters/Http/ServerRequest.php',
                "Zef\\Framework\\Http\\Stream" => __DIR__ . '/../src/Adapters/Http/Stream.php',
                "Zef\\Framework\\Http\\TrustedProxyMatcher" => __DIR__ . '/../src/Adapters/Http/TrustedProxyMatcher.php',
                "Zef\\Framework\\Http\\UploadedFile" => __DIR__ . '/../src/Adapters/Http/UploadedFile.php',
                "Zef\\Framework\\Http\\Uri" => __DIR__ . '/../src/Adapters/Http/Uri.php',
                "Zef\\Framework\\Job\\CronExpression" => __DIR__ . '/../src/Domain/Job/CronExpression.php',
                "Zef\\Framework\\Job\\FixedIntervalSchedule" => __DIR__ . '/../src/Domain/Job/FixedIntervalSchedule.php',
                "Zef\\Framework\\Job\\InMemoryJobIdempotencyStore" => __DIR__ . '/../src/Application/Job/InMemoryJobIdempotencyStore.php',
                "Zef\\Framework\\Job\\InMemoryJobQueue" => __DIR__ . '/../src/Application/Job/InMemoryJobQueue.php',
                "Zef\\Framework\\Job\\InProcessJobWorker" => __DIR__ . '/../src/Application/Job/InProcessJobWorker.php',
                "Zef\\Framework\\Job\\JobCancelledException" => __DIR__ . '/../src/Domain/Job/JobCancelledException.php',
                "Zef\\Framework\\Job\\JobContext" => __DIR__ . '/../src/Domain/Job/JobContext.php',
                "Zef\\Framework\\Job\\JobEnvelope" => __DIR__ . '/../src/Domain/Job/JobEnvelope.php',
                "Zef\\Framework\\Job\\JobExecutionException" => __DIR__ . '/../src/Domain/Job/JobExecutionException.php',
                "Zef\\Framework\\Job\\JobHandlerInterface" => __DIR__ . '/../src/Domain/Job/JobHandlerInterface.php',
                "Zef\\Framework\\Job\\JobIdempotencyStoreInterface" => __DIR__ . '/../src/Domain/Job/JobIdempotencyStoreInterface.php',
                "Zef\\Framework\\Job\\JobInterface" => __DIR__ . '/../src/Domain/Job/JobInterface.php',
                "Zef\\Framework\\Job\\JobMiddlewareInterface" => __DIR__ . '/../src/Domain/Job/JobMiddlewareInterface.php',
                "Zef\\Framework\\Job\\JobQueueInterface" => __DIR__ . '/../src/Domain/Job/JobQueueInterface.php',
                "Zef\\Framework\\Job\\JobResult" => __DIR__ . '/../src/Domain/Job/JobResult.php',
                "Zef\\Framework\\Job\\JobTimeoutException" => __DIR__ . '/../src/Domain/Job/JobTimeoutException.php',
                "Zef\\Framework\\Job\\RetryPolicy" => __DIR__ . '/../src/Domain/Job/RetryPolicy.php',
                "Zef\\Framework\\Job\\ScheduleInterface" => __DIR__ . '/../src/Domain/Job/ScheduleInterface.php',
                "Zef\\Framework\\Job\\Scheduler" => __DIR__ . '/../src/Application/Job/Scheduler.php',
                "Zef\\Framework\\Message\\DeduplicatingMiddleware" => __DIR__ . '/../src/Application/Message/DeduplicatingMiddleware.php',
                "Zef\\Framework\\Message\\InProcessMessageBus" => __DIR__ . '/../src/Application/Message/InProcessMessageBus.php',
                "Zef\\Framework\\Message\\JsonMessageSerializer" => __DIR__ . '/../src/Application/Message/JsonMessageSerializer.php',
                "Zef\\Framework\\Message\\MessageBusInterface" => __DIR__ . '/../src/Domain/Message/MessageBusInterface.php',
                "Zef\\Framework\\Message\\MessageContext" => __DIR__ . '/../src/Domain/Message/MessageContext.php',
                "Zef\\Framework\\Message\\MessageEnvelope" => __DIR__ . '/../src/Domain/Message/MessageEnvelope.php',
                "Zef\\Framework\\Message\\MessageHandlerInterface" => __DIR__ . '/../src/Domain/Message/MessageHandlerInterface.php',
                "Zef\\Framework\\Message\\MessageMiddlewareInterface" => __DIR__ . '/../src/Domain/Message/MessageMiddlewareInterface.php',
                "Zef\\Framework\\Message\\MessageResult" => __DIR__ . '/../src/Domain/Message/MessageResult.php',
                "Zef\\Framework\\Message\\MessageSerializerInterface" => __DIR__ . '/../src/Domain/Message/MessageSerializerInterface.php',
                "Zef\\Framework\\Message\\MessageTransportInterface" => __DIR__ . '/../src/Domain/Message/MessageTransportInterface.php',
                "Zef\\Framework\\MiddlewareDefinition" => __DIR__ . '/../src/Adapters/Kernel/MiddlewareDefinition.php',
                "Zef\\Framework\\MiddlewarePipeline" => __DIR__ . '/../src/Adapters/Kernel/MiddlewarePipeline.php',
                "Zef\\Framework\\ModuleBootstrapper" => __DIR__ . '/../src/Adapters/Kernel/ModuleBootstrapper.php',
                "Zef\\Framework\\Observability\\BatchSpanProcessor" => __DIR__ . '/../src/Application/Observability/BatchSpanProcessor.php',
                "Zef\\Framework\\Observability\\CorrelationContext" => __DIR__ . '/../src/Domain/Observability/CorrelationContext.php',
                "Zef\\Framework\\Observability\\CorrelationContextCarrierInterface" => __DIR__ . '/../src/Domain/Observability/CorrelationContextCarrierInterface.php',
                "Zef\\Framework\\Observability\\CorrelationHeaders" => __DIR__ . '/../src/Domain/Observability/CorrelationHeaders.php',
                "Zef\\Framework\\Observability\\CorrelationPropagator" => __DIR__ . '/../src/Application/Observability/CorrelationPropagator.php',
                "Zef\\Framework\\Observability\\CounterMeter" => __DIR__ . '/../src/Application/Observability/CounterMeter.php',
                "Zef\\Framework\\Observability\\ExplicitCorrelationContextCarrier" => __DIR__ . '/../src/Application/Observability/ExplicitCorrelationContextCarrier.php',
                "Zef\\Framework\\Observability\\HealthAggregator" => __DIR__ . '/../src/Application/Observability/HealthAggregator.php',
                "Zef\\Framework\\Observability\\HealthCheckResult" => __DIR__ . '/../src/Domain/Observability/HealthCheckResult.php',
                "Zef\\Framework\\Observability\\HealthIndicatorInterface" => __DIR__ . '/../src/Domain/Observability/HealthIndicatorInterface.php',
                "Zef\\Framework\\Observability\\InMemorySpanExporter" => __DIR__ . '/../src/Application/Observability/InMemorySpanExporter.php',
                "Zef\\Framework\\Observability\\LogExporterInterface" => __DIR__ . '/../src/Domain/Observability/LogExporterInterface.php',
                "Zef\\Framework\\Observability\\LogRecord" => __DIR__ . '/../src/Domain/Observability/LogRecord.php',
                "Zef\\Framework\\Observability\\MeterInterface" => __DIR__ . '/../src/Domain/Observability/MeterInterface.php',
                "Zef\\Framework\\Observability\\MetricExporterInterface" => __DIR__ . '/../src/Domain/Observability/MetricExporterInterface.php',
                "Zef\\Framework\\Observability\\NoopSpan" => __DIR__ . '/../src/Application/Observability/NoopSpan.php',
                "Zef\\Framework\\Observability\\NoopTracer" => __DIR__ . '/../src/Application/Observability/NoopTracer.php',
                "Zef\\Framework\\Observability\\OtlpHttpJsonExporter" => __DIR__ . '/../src/Infrastructure/Observability/OtlpHttpJsonExporter.php',
                "Zef\\Framework\\Observability\\PrometheusRenderer" => __DIR__ . '/../src/Infrastructure/Observability/PrometheusRenderer.php',
                "Zef\\Framework\\Observability\\RetryBackoffPolicy" => __DIR__ . '/../src/Domain/Observability/RetryBackoffPolicy.php',
                "Zef\\Framework\\Observability\\Span" => __DIR__ . '/../src/Application/Observability/Span.php',
                "Zef\\Framework\\Observability\\SpanContext" => __DIR__ . '/../src/Domain/Observability/SpanContext.php',
                "Zef\\Framework\\Observability\\SpanData" => __DIR__ . '/../src/Domain/Observability/SpanData.php',
                "Zef\\Framework\\Observability\\SpanExporterInterface" => __DIR__ . '/../src/Domain/Observability/SpanExporterInterface.php',
                "Zef\\Framework\\Observability\\SpanInterface" => __DIR__ . '/../src/Domain/Observability/SpanInterface.php',
                "Zef\\Framework\\Observability\\Telemetry" => __DIR__ . '/../src/Application/Observability/Telemetry.php',
                "Zef\\Framework\\Observability\\TelemetryClock" => __DIR__ . '/../src/Application/Observability/TelemetryClock.php',
                "Zef\\Framework\\Observability\\TelemetryLogger" => __DIR__ . '/../src/Application/Observability/TelemetryLogger.php',
                "Zef\\Framework\\Observability\\TelemetrySanitizer" => __DIR__ . '/../src/Application/Observability/TelemetrySanitizer.php',
                "Zef\\Framework\\Observability\\TraceContextPropagator" => __DIR__ . '/../src/Application/Observability/TraceContextPropagator.php',
                "Zef\\Framework\\Observability\\Tracer" => __DIR__ . '/../src/Application/Observability/Tracer.php',
                "Zef\\Framework\\Observability\\TracerInterface" => __DIR__ . '/../src/Domain/Observability/TracerInterface.php',
                "Zef\\Framework\\PipelineFactory" => __DIR__ . '/../src/Adapters/Kernel/PipelineFactory.php',
                "Zef\\Framework\\Policy\\ArchitecturePolicy" => __DIR__ . '/../src/Domain/Policy/ArchitecturePolicy.php',
                "Zef\\Framework\\Policy\\NamespaceScopePolicy" => __DIR__ . '/../src/Domain/Policy/NamespaceScopePolicy.php',
                "Zef\\Framework\\Resource\\AdmissionControllerInterface" => __DIR__ . '/../src/Domain/Resource/AdmissionControllerInterface.php',
                "Zef\\Framework\\Resource\\AdmissionDecision" => __DIR__ . '/../src/Domain/Resource/AdmissionDecision.php',
                "Zef\\Framework\\Resource\\AdmissionSnapshot" => __DIR__ . '/../src/Domain/Resource/AdmissionSnapshot.php',
                "Zef\\Framework\\Resource\\Cursor" => __DIR__ . '/../src/Domain/Resource/Cursor.php',
                "Zef\\Framework\\Resource\\FilterCondition" => __DIR__ . '/../src/Domain/Resource/FilterCondition.php',
                "Zef\\Framework\\Resource\\FilterSpec" => __DIR__ . '/../src/Domain/Resource/FilterSpec.php',
                "Zef\\Framework\\Resource\\InMemoryAdmissionController" => __DIR__ . '/../src/Application/Resource/InMemoryAdmissionController.php',
                "Zef\\Framework\\Resource\\PageRequest" => __DIR__ . '/../src/Domain/Resource/PageRequest.php',
                "Zef\\Framework\\Resource\\PageSlice" => __DIR__ . '/../src/Domain/Resource/PageSlice.php',
                "Zef\\Framework\\Resource\\ResourceBudget" => __DIR__ . '/../src/Domain/Resource/ResourceBudget.php',
                "Zef\\Framework\\Resource\\SortKey" => __DIR__ . '/../src/Domain/Resource/SortKey.php',
                "Zef\\Framework\\Resource\\SortSpec" => __DIR__ . '/../src/Domain/Resource/SortSpec.php',
                "Zef\\Framework\\ResponseEmitter" => __DIR__ . '/../src/Adapters/Kernel/ResponseEmitter.php',
                "Zef\\Framework\\Router\\RouteCache" => __DIR__ . '/../src/Adapters/Router/RouteCache.php',
                "Zef\\Framework\\Router\\RouteDefinition" => __DIR__ . '/../src/Adapters/Router/RouteDefinition.php',
                "Zef\\Framework\\Router\\Router" => __DIR__ . '/../src/Adapters/Router/Router.php',
                "Zef\\Framework\\Router\\UrlGenerator" => __DIR__ . '/../src/Adapters/Router/UrlGenerator.php',
                "Zef\\Framework\\Runtime\\BlockingSleeper" => __DIR__ . '/../src/Adapters/Runtime/BlockingSleeper.php',
                "Zef\\Framework\\Runtime\\InMemoryWorker" => __DIR__ . '/../src/Adapters/Runtime/InMemoryWorker.php',
                "Zef\\Framework\\Runtime\\RoadRunnerRuntime" => __DIR__ . '/../src/Adapters/Runtime/RoadRunnerRuntime.php',
                "Zef\\Framework\\Runtime\\RoadRunnerWorkerAdapter" => __DIR__ . '/../src/Adapters/Runtime/RoadRunnerWorkerAdapter.php',
                "Zef\\Framework\\Runtime\\RuntimeInterface" => __DIR__ . '/../src/Domain/Runtime/RuntimeInterface.php',
                "Zef\\Framework\\Runtime\\TinkerSession" => __DIR__ . '/../src/Adapters/Runtime/TinkerSession.php',
                "Zef\\Framework\\Runtime\\WorkerInterface" => __DIR__ . '/../src/Domain/Runtime/WorkerInterface.php',
                "Zef\\Framework\\Security\\AesGcmEncryptor" => __DIR__ . '/../src/Infrastructure/Security/AesGcmEncryptor.php',
                "Zef\\Framework\\Security\\ApcuRateLimiter" => __DIR__ . '/../src/Infrastructure/Security/ApcuRateLimiter.php',
                "Zef\\Framework\\Security\\AuthenticationMiddleware" => __DIR__ . '/../src/Adapters/Security/AuthenticationMiddleware.php',
                "Zef\\Framework\\Security\\Base32" => __DIR__ . '/../src/Domain/Security/Base32.php',
                "Zef\\Framework\\Security\\ClientAddressResolver" => __DIR__ . '/../src/Application/Security/ClientAddressResolver.php',
                "Zef\\Framework\\Security\\CsrfTokenManager" => __DIR__ . '/../src/Application/Security/CsrfTokenManager.php',
                "Zef\\Framework\\Security\\Distributed\\AllowScopeAuthorizationPolicy" => __DIR__ . '/../src/Application/Security/Distributed/AllowScopeAuthorizationPolicy.php',
                "Zef\\Framework\\Security\\Distributed\\AuthenticationResult" => __DIR__ . '/../src/Domain/Security/Distributed/AuthenticationResult.php',
                "Zef\\Framework\\Security\\Distributed\\AuthenticationStatus" => __DIR__ . '/../src/Domain/Security/Distributed/AuthenticationStatus.php',
                "Zef\\Framework\\Security\\Distributed\\AuthorizationPolicyInterface" => __DIR__ . '/../src/Domain/Security/Distributed/AuthorizationPolicyInterface.php',
                "Zef\\Framework\\Security\\Distributed\\AuthorizationResult" => __DIR__ . '/../src/Domain/Security/Distributed/AuthorizationResult.php',
                "Zef\\Framework\\Security\\Distributed\\BoundedInMemoryReplayProtector" => __DIR__ . '/../src/Application/Security/Distributed/BoundedInMemoryReplayProtector.php',
                "Zef\\Framework\\Security\\Distributed\\BoundedTrait" => __DIR__ . '/../src/Domain/Security/Distributed/BoundedTrait.php',
                "Zef\\Framework\\Security\\Distributed\\CredentialHandle" => __DIR__ . '/../src/Domain/Security/Distributed/CredentialHandle.php',
                "Zef\\Framework\\Security\\Distributed\\CredentialProviderInterface" => __DIR__ . '/../src/Domain/Security/Distributed/CredentialProviderInterface.php',
                "Zef\\Framework\\Security\\Distributed\\DefaultSecurityBoundary" => __DIR__ . '/../src/Application/Security/Distributed/DefaultSecurityBoundary.php',
                "Zef\\Framework\\Security\\Distributed\\ReplayDecision" => __DIR__ . '/../src/Domain/Security/Distributed/ReplayDecision.php',
                "Zef\\Framework\\Security\\Distributed\\ReplayProtectorInterface" => __DIR__ . '/../src/Domain/Security/Distributed/ReplayProtectorInterface.php',
                "Zef\\Framework\\Security\\Distributed\\ReplayResult" => __DIR__ . '/../src/Domain/Security/Distributed/ReplayResult.php',
                "Zef\\Framework\\Security\\Distributed\\SecurityAdmissionDecision" => __DIR__ . '/../src/Domain/Security/Distributed/SecurityAdmissionDecision.php',
                "Zef\\Framework\\Security\\Distributed\\SecurityBoundaryInterface" => __DIR__ . '/../src/Domain/Security/Distributed/SecurityBoundaryInterface.php',
                "Zef\\Framework\\Security\\Distributed\\SecurityContext" => __DIR__ . '/../src/Domain/Security/Distributed/SecurityContext.php',
                "Zef\\Framework\\Security\\Distributed\\SecurityFailure" => __DIR__ . '/../src/Domain/Security/Distributed/SecurityFailure.php',
                "Zef\\Framework\\Security\\Distributed\\SecurityRequest" => __DIR__ . '/../src/Domain/Security/Distributed/SecurityRequest.php',
                "Zef\\Framework\\Security\\Distributed\\SecurityVerdict" => __DIR__ . '/../src/Domain/Security/Distributed/SecurityVerdict.php',
                "Zef\\Framework\\Security\\Distributed\\StaticCredentialProvider" => __DIR__ . '/../src/Application/Security/Distributed/StaticCredentialProvider.php',
                "Zef\\Framework\\Security\\EncryptionInterface" => __DIR__ . '/../src/Domain/Security/EncryptionInterface.php',
                "Zef\\Framework\\Security\\InMemoryRateLimiter" => __DIR__ . '/../src/Application/Security/InMemoryRateLimiter.php',
                "Zef\\Framework\\Security\\OriginPolicy" => __DIR__ . '/../src/Application/Security/OriginPolicy.php',
                "Zef\\Framework\\Security\\RateLimitDecision" => __DIR__ . '/../src/Domain/Security/RateLimitDecision.php',
                "Zef\\Framework\\Security\\RateLimiterInterface" => __DIR__ . '/../src/Domain/Security/RateLimiterInterface.php',
                "Zef\\Framework\\Security\\RedisRateLimiter" => __DIR__ . '/../src/Infrastructure/Security/RedisRateLimiter.php',
                "Zef\\Framework\\Security\\RedisSharedRateLimitStore" => __DIR__ . '/../src/Infrastructure/Security/RedisSharedRateLimitStore.php',
                "Zef\\Framework\\Security\\RotatingKeyRing" => __DIR__ . '/../src/Infrastructure/Security/RotatingKeyRing.php',
                "Zef\\Framework\\Security\\SecurityContext" => __DIR__ . '/../src/Domain/Security/SecurityContext.php',
                "Zef\\Framework\\Security\\SecurityPolicy" => __DIR__ . '/../src/Domain/Security/SecurityPolicy.php',
                "Zef\\Framework\\Security\\SecurityRuntimeMiddleware" => __DIR__ . '/../src/Adapters/Security/SecurityRuntimeMiddleware.php',
                "Zef\\Framework\\Security\\SharedRateLimitStoreInterface" => __DIR__ . '/../src/Domain/Security/SharedRateLimitStoreInterface.php',
                "Zef\\Framework\\Security\\Totp" => __DIR__ . '/../src/Domain/Security/Totp.php',
                "Zef\\Framework\\Validation\\DependencyGraphValidator" => __DIR__ . '/../src/Domain/Validation/DependencyGraphValidator.php',
                "Zef\\Framework\\Validation\\FieldRules" => __DIR__ . '/../src/Domain/Validation/FieldRules.php',
                "Zef\\Framework\\Validation\\HeaderValidator" => __DIR__ . '/../src/Domain/Validation/HeaderValidator.php',
                "Zef\\Framework\\Validation\\HttpMethodValidator" => __DIR__ . '/../src/Domain/Validation/HttpMethodValidator.php',
                "Zef\\Framework\\Validation\\HttpStatusValidator" => __DIR__ . '/../src/Domain/Validation/HttpStatusValidator.php',
                "Zef\\Framework\\Validation\\Identifier" => __DIR__ . '/../src/Domain/Validation/Identifier.php',
                "Zef\\Framework\\Validation\\MessageCatalog" => __DIR__ . '/../src/Domain/Validation/MessageCatalog.php',
                "Zef\\Framework\\Validation\\PortRangeValidator" => __DIR__ . '/../src/Domain/Validation/PortRangeValidator.php',
                "Zef\\Framework\\Validation\\RouteConstraintValidator" => __DIR__ . '/../src/Domain/Validation/RouteConstraintValidator.php',
                "Zef\\Framework\\Validation\\TrustedHostValidator" => __DIR__ . '/../src/Domain/Validation/TrustedHostValidator.php',
                "Zef\\Framework\\Validation\\ValidationError" => __DIR__ . '/../src/Domain/Validation/ValidationError.php',
                "Zef\\Framework\\Validation\\ValidationResult" => __DIR__ . '/../src/Domain/Validation/ValidationResult.php',
                "Zef\\Framework\\Validation\\ValidationTranslator" => __DIR__ . '/../src/Domain/Validation/ValidationTranslator.php',
                "Zef\\Framework\\Validation\\Validator" => __DIR__ . '/../src/Domain/Validation/Validator.php',
                "Zef\\Middleware\\ConfigProvider" => __DIR__ . '/../src/Middleware/ConfigProvider.php',
                "Zef\\Middleware\\CorsMiddleware" => __DIR__ . '/../src/Middleware/CorsMiddleware.php',
                "Zef\\Middleware\\ErrorLogger" => __DIR__ . '/../src/Middleware/ErrorLogger.php',
                "Zef\\Middleware\\ErrorResponseFactory" => __DIR__ . '/../src/Middleware/ErrorResponseFactory.php',
                "Zef\\Middleware\\GlobalErrorHandler" => __DIR__ . '/../src/Middleware/GlobalErrorHandler.php',
                "Zef\\Middleware\\SecurityHeadersMiddleware" => __DIR__ . '/../src/Middleware/SecurityHeadersMiddleware.php',
                "Zef\\Middleware\\TimingMiddleware" => __DIR__ . '/../src/Middleware/TimingMiddleware.php',
                "Zef\\Module\\Core\\AboutHandler" => __DIR__ . '/../modules/Core/AboutHandler.php',
                "Zef\\Module\\Core\\ConfigProvider" => __DIR__ . '/../modules/Core/ConfigProvider.php',
                "Zef\\Module\\Core\\HomeHandler" => __DIR__ . '/../modules/Core/HomeHandler.php',
                "Zef\\Module\\Health\\AggregateHealthHandler" => __DIR__ . '/../modules/Health/AggregateHealthHandler.php',
                "Zef\\Module\\Health\\CanaryService" => __DIR__ . '/../modules/Health/CanaryService.php',
                "Zef\\Module\\Health\\ConfigProvider" => __DIR__ . '/../modules/Health/ConfigProvider.php',
                "Zef\\Module\\Health\\ContainerHealthIndicator" => __DIR__ . '/../modules/Health/ContainerHealthIndicator.php',
                "Zef\\Module\\Health\\LiveHandler" => __DIR__ . '/../modules/Health/LiveHandler.php',
                "Zef\\Module\\Health\\MetricsHandler" => __DIR__ . '/../modules/Health/MetricsHandler.php',
                "Zef\\Module\\Health\\ReadyHandler" => __DIR__ . '/../modules/Health/ReadyHandler.php',
                "Zef\\Plugin\\Toko\\ConfigProvider" => __DIR__ . '/../plugins/Toko/ConfigProvider.php',
                "Zef\\Plugin\\Toko\\ProdukDetailHandler" => __DIR__ . '/../plugins/Toko/ProdukDetailHandler.php',
                "Zef\\Plugin\\Toko\\ProdukService" => __DIR__ . '/../plugins/Toko/ProdukService.php',
                "Zef\\Plugin\\Toko\\TokoHandler" => __DIR__ . '/../plugins/Toko/TokoHandler.php',
                "Zef\\Test\\CacheProbe" => __DIR__ . '/../tests/V2110RadixTreeSuite.php',
                "Zef\\Test\\CliRunner" => __DIR__ . '/../tests/CliRunner.php',
                "Zef\\Test\\ClockProbe" => __DIR__ . '/../tests/V2110RadixTreeSuite.php',
                "Zef\\Test\\DbProbe" => __DIR__ . '/../tests/V2110RadixTreeSuite.php',
                "Zef\\Test\\DeepUnmappedService" => __DIR__ . '/../tests/V2110RadixTreeSuite.php',
                "Zef\\Test\\MiddlewareProbe" => __DIR__ . '/../tests/V2110RadixTreeSuite.php',
                "Zef\\Test\\UnmappedService" => __DIR__ . '/../tests/V2110RadixTreeSuite.php',
                "Zef\\Test\\UserHandlerProbe" => __DIR__ . '/../tests/V2110RadixTreeSuite.php',
                "Zef\\Test\\V2100EnterpriseSuite" => __DIR__ . '/../tests/V2100EnterpriseSuite.php',
                "Zef\\Test\\V2110RadixTreeSuite" => __DIR__ . '/../tests/V2110RadixTreeSuite.php',
                "Zef\\Test\\V270IdemCmd" => __DIR__ . '/../tests/V270IdemCmd.php',
                "Zef\\Test\\V270MagicEvent" => __DIR__ . '/../tests/V270MagicEvent.php',
                "Zef\\Test\\V270ReCmd" => __DIR__ . '/../tests/V270ReCmd.php',
                "Zef\\Test\\V280FeatureSuite" => __DIR__ . '/../tests/V280FeatureSuite.php',
                "Zef\\Test\\V290AbstractBase" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290AlphaConsumer" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290ArrayCache" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290AuditHandler" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290AutowireSuite" => __DIR__ . '/../tests/V290AutowireSuite.php',
                "Zef\\Test\\V290BetaOne" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290BetaTwo" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290BoomService" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290CacheInterface" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290CacheUser" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290CronHandler" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290CycleA" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290CycleB" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290DbRepo" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290HandlerInterface" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290HttpConfig" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290Leaf" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290MailHandler" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290Middle" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290NamedDep" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290OptionalMiddle" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290Pipeline" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290QueueHandler" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290RepoConsumer" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290RepoInterface" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290Root" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290ScalarPipeline" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290SecretKey" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290UnboundOptional" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290UnionDep" => __DIR__ . '/../tests/V290AutowireFixtures.php',
                "Zef\\Test\\V290Vault" => __DIR__ . '/../tests/V290AutowireFixtures.php',
            ];
        }
        if (isset($map[$class])) {
            require_once $map[$class];
        }
    }

    spl_autoload_register('zef_framework_autoload');

    // Eager PSR shims (guarded — mirrors the original monolith behaviour).
    foreach ([
        __DIR__ . '/../src/Compat/Psr/Container/ContainerExceptionInterface.php',
        __DIR__ . '/../src/Compat/Psr/Container/ContainerInterface.php',
        __DIR__ . '/../src/Compat/Psr/Container/NotFoundExceptionInterface.php',
        __DIR__ . '/../src/Compat/Psr/EventDispatcher/EventDispatcherInterface.php',
        __DIR__ . '/../src/Compat/Psr/EventDispatcher/ListenerProviderInterface.php',
        __DIR__ . '/../src/Compat/Psr/EventDispatcher/StoppableEventInterface.php',
        __DIR__ . '/../src/Compat/Psr/Http/Message/MessageInterface.php',
        __DIR__ . '/../src/Compat/Psr/Http/Message/RequestFactoryInterface.php',
        __DIR__ . '/../src/Compat/Psr/Http/Message/RequestInterface.php',
        __DIR__ . '/../src/Compat/Psr/Http/Message/ResponseFactoryInterface.php',
        __DIR__ . '/../src/Compat/Psr/Http/Message/ResponseInterface.php',
        __DIR__ . '/../src/Compat/Psr/Http/Message/ServerRequestFactoryInterface.php',
        __DIR__ . '/../src/Compat/Psr/Http/Message/ServerRequestInterface.php',
        __DIR__ . '/../src/Compat/Psr/Http/Message/StreamFactoryInterface.php',
        __DIR__ . '/../src/Compat/Psr/Http/Message/StreamInterface.php',
        __DIR__ . '/../src/Compat/Psr/Http/Message/UploadedFileFactoryInterface.php',
        __DIR__ . '/../src/Compat/Psr/Http/Message/UploadedFileInterface.php',
        __DIR__ . '/../src/Compat/Psr/Http/Message/UriFactoryInterface.php',
        __DIR__ . '/../src/Compat/Psr/Http/Message/UriInterface.php',
        __DIR__ . '/../src/Compat/Psr/Http/Server/MiddlewareInterface.php',
        __DIR__ . '/../src/Compat/Psr/Http/Server/RequestHandlerInterface.php',
        __DIR__ . '/../src/Compat/Psr/Log/LoggerInterface.php',
        __DIR__ . '/../src/Compat/Psr/Log/NullLogger.php',
    ] as $shimFile) {
        require_once $shimFile;
    }
}
