<?php

declare(strict_types=1);

/*
 * ZEF Framework v2.29.0 — Infrastructure layer (outbound adapters).
 * ZEF Maker: generate/refresh the RoadRunner `.rr.yaml` from documented
 * ZEF_* env knobs and CLI flags (`bin/zef rr:init`). The goal is RoadRunner
 * transparency: a developer never hand-edits worker pool configuration to
 * get a production-style runtime.
 *
 * Precedence (highest wins): CLI flag > environment knob > built-in default.
 * Existing files are never overwritten without --force (collision-safe).
 */

namespace Zef\Framework\Console\Generator;

use Zef\Framework\Console\ConsoleIO;
use Zef\Framework\Console\GeneratorInterface;
use Zef\Framework\Console\ScaffoldCollisionException;
use Zef\Framework\Console\ScaffoldWriter;

final readonly class RoadRunnerConfigGenerator implements GeneratorInterface
{
    private const string ADDRESS_PATTERN = '/^[0-9.]+:[0-9]{1,5}$/';
    private const string ADDRESS_PATTERN_V6 = '/^\[[0-9a-f:]+\]:[0-9]{1,5}$/';

    public function __construct(
        private string $root,
        private ConsoleIO $io,
        private ScaffoldWriter $writer,
    ) {}

    public function generate(?string $rawName, array $argv = []): int
    {
        $path = "{$this->root}/.rr.yaml";
        $force = in_array('--force', $argv, true);

        if (!$force && is_file($path)) {
            $this->io->err(".rr.yaml already exists ({$path}). Use --force to regenerate it.");

            return 1;
        }

        $address = $this->option($argv, 'address') ?? $this->envString('ZEF_HTTP_ADDRESS');
        $workers = $this->intOption($argv, 'workers', $this->envString('ZEF_RR_NUM_WORKERS')) ?? 4;
        $maxJobs = $this->intOption($argv, 'max-jobs', $this->envString('ZEF_WORKER_MAX_JOBS')) ?? 0;
        $memory = $this->intOption($argv, 'memory', $this->envString('ZEF_WORKER_MEMORY_LIMIT')) ?? 512;

        $address ??= '0.0.0.0:8080';
        if (preg_match(self::ADDRESS_PATTERN, $address) !== 1 && preg_match(self::ADDRESS_PATTERN_V6, $address) !== 1) {
            $this->io->err("Invalid --address '{$address}'. Expected host:port (e.g. 0.0.0.0:8080).");

            return 1;
        }
        if ($workers < 1 || $workers > 1024) {
            $this->io->err("Invalid --workers '{$workers}'. Expected an integer between 1 and 1024.");

            return 1;
        }
        if ($maxJobs < 0) {
            $this->io->err("Invalid --max-jobs '{$maxJobs}'. Expected >= 0 (0 = unlimited).");

            return 1;
        }
        if ($memory < 0) {
            $this->io->err("Invalid --memory '{$memory}'. Expected >= 0 MB (0 = disabled).");

            return 1;
        }

        try {
            $rendered = $this->render($address, $workers, $maxJobs, $memory);
            if ($force && is_file($path)) {
                $this->writer->overwriteFile($path, $rendered);
            } else {
                $this->writer->writeFile($path, $rendered);
            }
        } catch (ScaffoldCollisionException $e) {
            $this->io->err($e->getMessage());

            return 1;
        }

        $this->io->out(<<<TXT

            RoadRunner config written to {$path}.

            Next steps:
              1. Install the RoadRunner binary (one-time):
                 https://docs.roadrunner.dev/docs/general/install
              2. vendor/bin/rr serve -c .rr.yaml

            TXT);

        return 0;
    }

    private function render(string $address, int $workers, int $maxJobs, int $memory): string
    {
        $maxJobsPhp = $maxJobs === 0 ? '0' : (string) $maxJobs;

        return <<<YAML
            # RoadRunner v2025.1 configuration for ZEF Framework.
            # Generated by: bin/zef rr:init (re-run with --force to refresh).
            # Worker:      bin/worker.php (bridge spiral/roadrunner-http + nyholm/psr7)

            version: "2025.1"

            server:
              command: "php bin/worker.php"
              relay: "pipes"

            http:
              # Public address of the RoadRunner server.
              address: {$address}
              # Built-in RR middleware; add "static" to serve public/ directly.
              middleware: [ "gzip" ]
              pool:
                # PHP worker count; calibrate to your CPU.
                num_workers: {$workers}
                max_jobs: {$maxJobsPhp}          # 0 = unlimited; mirrors ZEF_WORKER_MAX_JOBS
                supervisor:
                  max_worker_memory: {$memory}   # MB per worker (0 = disabled)

            logs:
              mode: development
              level: info
              encoding: console

            YAML;
    }

    /** Non-empty string value of an environment knob, or null. */
    private function envString(string $name): ?string
    {
        $value = getenv($name);

        return is_string($value) && $value !== '' ? $value : null;
    }

    /**
     * @param array<int, mixed> $argv
     */
    private function option(array $argv, string $key): ?string
    {
        foreach ($argv as $arg) {
            if (!is_string($arg)) {
                continue;
            }
            if (str_starts_with($arg, "--{$key}=")) {
                $value = substr($arg, strlen($key) + 3);

                return $value === '' ? null : $value;
            }
        }

        return null;
    }

    /** `--key=N` flag first, then an env fallback string, else null. */
    /**
     * @param array<int, mixed> $argv
     */
    private function intOption(array $argv, string $key, ?string $envFallback): ?int
    {
        $raw = $this->option($argv, $key) ?? $envFallback;
        if ($raw === null || trim($raw) === '' || preg_match('/^[0-9]+$/', $raw) !== 1) {
            return null;
        }

        return (int) $raw;
    }
}
